name: try2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  collection: ^1.19.1
  fl_chart: ^0.71.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_masked_text2: ^0.9.1
  intl: ^0.20.2
  path_provider: ^2.1.5
  sqflite: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/bca.jpg 
    - assets/gopay.webp
    - assets/Khursus.jpg
    - assets/Ovo.webp
    - assets/UKT.jpg
    - assets/dom.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/dom.png"
